### ISSUE TITLE
Received Messages filling entire width and not round like sent ones

### ISSUE THREAD

**Issue by rutura** [timigod/android-chat-ui#16]
Screen below 
![image](https://user-images.githubusercontent.com/24886515/32207463-00404bea-be37-11e7-85a9-40b92f679764.png)

**Comment by mohan083** [comment]
I am having the same issue.

**Comment by MichaelObi** [comment]
I'm going to try to reproduce this now. I'll ask if I need more information to do that.

**Comment by luciovinicius** [comment]
any solutions? same here

**Comment by andkishor** [comment]
Any updates on it?

**Comment by mattplindsay** [comment]
I receive the same issue - has anyone worked out why?

**Comment by samuelo-101** [comment]
Had this issue but was able to workaround it by adding the following attribute to the ChatView in my XML layout:
`chatview:bubbleBackgroundRcv="#SomeHexCode"` 

However, the bubble background is black for received messages, even though I have explicitly set it to another color.
![screenshot](https://user-images.githubusercontent.com/1647485/38148187-aee6a196-3455-11e8-8e8d-02482b65f1e4.png)

**Comment by mattplindsay** [comment]
Thanks for that answer. Unfortunately that didn't work for me. I was using the following code:
`    <co.intentservice.chatui.ChatView
        android:id="@+id/my_chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chatview:bubbleBackgroundRcv="#ffffff"
        />`

**Comment by samuelo-101** [comment]
@mattplindsay Haven't gone through the code to see exactly what might be causing the issue, but perhaps a combination of attributes might work. This is what I have in place:
`<co.intentservice.chatui.ChatView
        android:id="@+id/chatView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        chatview:backgroundColor="@color/white"
        chatview:bubbleBackgroundRcv="@color/white"
        chatview:bubbleBackgroundSend="@color/white"
        chatview:bubbleElevation="elevated"
        chatview:inputBackgroundColor="@color/white"
        chatview:inputHintColor="@color/grey"
        chatview:inputTextColor="@color/textColor"
        chatview:sendBtnBackgroundTint="@color/colorPrimary"
        chatview:sendBtnIconTint="@color/white" />`

**Comment by mattplindsay** [comment]
Yes, I have fixed the 'full width' problem by fixing a typo I had in:
`xmlns:chatview="http://schemas.android.com/apk/res-auto"`

But I still that the same issue as you in that:
`chatview:bubbleBackgroundRcv="@color/white"`

Still doesn't do anything (my bubbles are still black) - but at least it;s better

**Comment by samuelo-101** [comment]
@mattplindsay I cloned the project and discovered a posible bug in the View Holder class `co.intentservice.chatui.viewholders. MessageViewHolder` line 72:

`messageView.setBackgroundColor(background);` should actually be `messageView.setBackground(background);` to have any effect on the bubble.

setBackgroundColor calls the View superclass, which will ultimately change the background color of the row, but to have an effect on the bubble, setBackground should be called instead. Tested with `chatview:bubbleBackgroundRcv="#4CAF50"`

If anyone else can validate this, please do. I will branch and create a pull request ASAP.
See attached screenshot:
![screen](https://user-images.githubusercontent.com/1647485/38448006-81c3d04c-3a01-11e8-92e2-48e34d17a714.png)

**Comment by samuelo-101** [comment]
@timigod @MichaelObi Hi. I've opened a pull request with respect to this issue. Kindly review when possible. Thanks.
https://github.com/timigod/android-chat-ui/pull/22/commits

**Comment by MichaelObi** [comment]
The issues here have been addressed by PR #22.

Closing this now.
