### ISSUE TITLE
Bubble colors not changing

### ISSUE THREAD

**Issue by rijulluman** [timigod/android-chat-ui#23]
Hi,
I am trying to change the bubble colors, but they are not changing... Is anyone else facing the same issue ?
I am adding the following:
```
<co.intentservice.chatui.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chatview:bubbleElevation="elevated"
        chatview:bubbleBackgroundRcv="@color/white"
        chatview:bubbleBackgroundSend="@color/white"
        chatview:backgroundRcv="@color/white"
        chatview:messageTextColorSend="@color/blue"
    />
```

**Comment by rijulluman** [comment]
Got the bubble color by using master branch instead of the 0.1.3 tag:
`implementation 'com.github.timigod:android-chat-ui:master'`

xml:
```
<co.intentservice.chatui.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chatview:bubbleElevation="elevated"
        chatview:bubbleBackgroundRcv="@color/accent_color"
        chatview:bubbleBackgroundSend="@color/white"
        chatview:messageTextColorRcv="@color/black"
        chatview:inputTextColor="@color/black"
        chatview:backgroundRcv="@color/greyish"
        chatview:backgroundSend="@color/greyish"
        chatview:backgroundColor="@color/greyish"

    />
```

But the messageText color is still not changing for both sent and received

**Comment by ousanmazCT** [comment]
implementation 'com.github.timigod:android-chat-ui:master' worked for me too, also I had to paint the backgrounds white to get the ui I want:

    <co.intentservice.chatui.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chatview:backgroundColor="@color/white"
        chatview:bubbleBackgroundRcv="@color/colorPrimary"
        chatview:bubbleBackgroundSend="@color/white"
        chatview:bubbleElevation="elevated"
        chatview:inputBackgroundColor="@color/transparent"
        chatview:inputHintColor="@color/grey"
        chatview:inputTextColor="@color/black"
        chatview:inputUseEditorAction="true"
        chatview:sendBtnIcon="@drawable/send"
        chatview:backgroundRcv="@color/white"
        chatview:backgroundSend="@color/white"/>

**Comment by ivanov84** [comment]
Need to use in your template exactly this line:
xmlns:chatView="http://schemas.android.com/apk/res-auto"
