### ISSUE TITLE
Listview updation refresh issue

### ISSUE THREAD

**Issue by shrujalr** [timigod/android-chat-ui#25]
Hello ,
I am  facing issues regarding the refresh of list view after adding every message.
Everytime  a message is received in the ui, only after refreshing the ui the message will be displayed.
Kindly help me  out with this issue.

**Comment by MichaelObi** [comment]
Hi @shrujalr, What version of the library do you have included in your project?

**Comment by ingloriousb** [comment]
Facing the exact same issue, using library v0.1.4

**Comment by MichaelObi** [comment]
Hi @ingloriousb,
Is there any other info you think will help me reproduce this issue?

**Comment by shrujalr** [comment]
My issue is solved . It has nothing to do with the UI library . Thanks
though !

**Comment by ingloriousb** [comment]
@shrujalr How did you solve it?

**Comment by shrujalr** [comment]
I had to put the updation of UI in some thread . I will check it once and
will update on the same

**Comment by ingloriousb** [comment]
Thanks a ton. 👍 Eagerly awaiting the update

**Comment by shrujalr** [comment]
new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            ChatMessage chatMessage = new ChatMessage(body.get(0).getTextContent().toString(), System.currentTimeMillis(), ChatMessage.Type.RECEIVED);
                            mChatView.addMessage(chatMessage);
                        }
                    });
This is the code which i mentioned earlier

**Comment by MichaelObi** [comment]
Nice.
Is it now okay to close this issue?

**Comment by ingloriousb** [comment]
Yes. :) Thanks to both of you.


On 13-Jul-2018, at 4:12 PM, Michael Obi <notifications@github.com> wrote:

Nice.
Is it now okay to close this issue?
