### ISSUE TITLE
The Bubble messages has a white backgroundcolor which doesnt change when changing chatbackgroundcolor. How to fix this

### ISSUE THREAD

**Issue by Tobibur** [timigod/android-chat-ui#31]
![screenshot_1533532128](https://user-images.githubusercontent.com/20985483/43697987-449fb262-9965-11e8-8674-52fd559bcd89.png)
![screenshot_1533532164](https://user-images.githubusercontent.com/20985483/43697992-49f7e5c2-9965-11e8-864b-d5949306ed9b.png)

**Comment by MichaelObi** [comment]
Hi @Tobibur,
I'm sorry you're experiencing this. Just a few questions to get some context
What version of the library do you have in your project?
Can you provide a snippet showing how you included the ChatView in your layout?

**Comment by Tobibur** [comment]
my layout
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:chatview="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"

    style="@style/Widget.AppCompat.ButtonBar"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    tools:context=".view.activities.ChatActivity">

    <co.intentservice.chatui.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chatview:backgroundColor="#4DB6AC"
        chatview:bubbleElevation="elevated"
        chatview:bubbleBackgroundRcv="@color/blue"
        chatview:bubbleBackgroundSend="@color/white"
        chatview:inputHint="@string/start_typing"/>

</LinearLayout>
```

I am using this version:
```
implementation ('com.github.timigod:android-chat-ui:v0.1.4'){
        exclude module: 'support-v4'
    }
```

**Comment by samuelo-101** [comment]
Hi, @Tobibur 
Please try specifying colors for the attributes "chatview:backgroundRcv" and "chatview:backgroundSend" in your XML layout. Something like:

`chatview:backgroundRcv="@color/blue"
  chatview:backgroundSend="@color/white"`

**Comment by Tobibur** [comment]
Hi, @samuelojo88 
Yes, this worked. Thanks for answering.
![chatscreenshot](https://user-images.githubusercontent.com/20985483/45488371-d4473980-b77e-11e8-971b-897447f1e162.png)

**Comment by samuelo-101** [comment]
@Tobibur You're welcome bro :-)
