### ISSUE TITLE
Message sent/seen status

### ISSUE THREAD

**Issue by androwed** [timigod/android-chat-ui#8]
Very grateful for such complete UI library, is there any way to set status of message sent/seen in the bubble. I have the code for message delivery and receipt, I just want to implement in the ChatView. My App would be complete if I can do it. Thanks.

**Comment by androwed** [comment]
I would like to contribute, I know what to do but kindly guide me how can I ? Sorry no idea about Github.

**Comment by timigod** [comment]
https://github.com/IntentService/android-chat-ui#contributing
